name: Scheduled Sync

on:
  schedule:
    - cron: '0 */3 * * *' # Запуск каждые 3 часа.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_FORK_TOKEN }} # Используется секретный ключ синхронизации форка.
          fetch-depth: 0

      - name: Add upstream and sync
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/SoliSpirit/mtproto.git
          git fetch upstream
          git checkout master
          git merge upstream/master --ff-only || git merge upstream/master
          git push origin master
